- [ ] only bind ~execute-doctest~ for Python mode
- [ ] rename repo dir to ~pydor~
- [ ] support ~verbose~ option
- [ ] use logging instead of ~print~
- [ ] properly parse command-line parameters
- [ ] setup proper Python development environment using Poetry
- [ ] format Lisp code according to Batsov style guide
- [ ] make it work for Python modules in another package (when package is not in search path)
- [ ] for tests, leave visited file on teardown

- [ ] make it work for Python modules in another package (when package is in search path)

This should work but real-world testing is necessary.

- [ ] add README

* Done

- [X] make it work for Python modules in another subdirectory
- [X] let Lisp code use full path to ~use_finder.py~
- [X] setup proper Emacs Lisp development environment using Cask

I used Eask instead of Cask. Although up till now I used Cask, the lack of
up-to-date documentation was grating. Eask, which labels itself as a successor
to Cask, has a very similar interface, was easy to install and use.

- [X] retrieve module name in script
